#!/usr/bin/env python3
"""
GÖRSEL İSTEM KÜTÜPHANESİ — The Great Book of World Games
================================================================================
`07_ASSETS/IMAGE_PROMPT_LIBRARY.html` üretir: kurucunun görselleri dışarıda
üretirken kullanacağı **kanonik istem kütüphanesi**.

⚠ GEÇMİŞ SİLİNMEZ. Dosya bölümlere ayrılmıştır ve her bölüm bir işaretle
çevrilidir:

    <!-- SECTION:<id> --> … <!-- /SECTION:<id> -->

Bu betik YALNIZCA kendi bölümünü yeniden yazar; dosyadaki başka her şey
byte-byte korunur. Bir istem kütüphanesinin değeri, reddedilen istemleri de
taşımasındadır: aynı hatanın ikinci kez yapılmasını o kayıt engeller.

⚠ SAYI YAZILMAZ, BASILIR. Sırt genişliği, sarım ölçüsü ve güvenli alanların
hepsi `06_REPORTS/cover-geometry.json` içinden gelir — ki o da ÖLÇÜLEN sayfa
sayısından hesaplanır. Bir isteme elle yazılmış piksel değeri, iç blok bir
sayfa değiştiğinde sessizce yalancı olur.

Çıkış kodları:  0 = üretildi   1 = üretilemedi   2 = kullanım hatası
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

SECTION_ID = "phase6-cover-aplus"
OUT_REL = os.path.join("07_ASSETS", "IMAGE_PROMPT_LIBRARY.html")


def load(p):
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def E(s):
    return html.escape(str(s))


def ul(items, cls=""):
    return ('<ul class="%s">' % cls) + "".join(
        "<li>%s</li>" % E(i) for i in items) + "</ul>"


def kv(rows):
    return ("<table class=spec><tbody>" + "".join(
        "<tr><th>%s</th><td>%s</td></tr>" % (E(k), v if isinstance(v, str)
                                             and v.startswith("<") else E(v))
        for k, v in rows) + "</tbody></table>")


SHELL = """<meta charset="utf-8">
<title>Image Prompt Library — The Great Book of World Games</title>
<style>
:root{--ink:#1b1a17;--mut:#6b675e;--pap:#faf8f3;--line:#ddd8cc;--warn:#8a2f1d;
      --ok:#2c5e3f;--code:#f3efe6}
*{box-sizing:border-box}
body{margin:0;background:var(--pap);color:var(--ink);
     font:16px/1.6 Georgia,'Liberation Serif',serif;padding:0 0 6rem}
.wrap{max-width:64rem;margin:0 auto;padding:0 1.5rem}
h1{font-size:2rem;line-height:1.2;margin:2.5rem 0 .3rem}
h2{font-size:1.35rem;margin:3rem 0 .6rem;padding-top:1.2rem;
   border-top:2px solid var(--ink)}
h3{font-size:1.1rem;margin:2rem 0 .4rem}
h4{font-size:.95rem;margin:1.4rem 0 .3rem;text-transform:uppercase;
   letter-spacing:.06em;color:var(--mut)}
p{margin:.6rem 0}
.lede{color:var(--mut);font-size:1.05rem}
ul{margin:.4rem 0 .8rem;padding-left:1.3rem}
li{margin:.25rem 0}
.no li{color:var(--warn)}
.avoid li{color:var(--mut)}
table.spec{border-collapse:collapse;width:100%;margin:.8rem 0;font-size:.9rem}
table.spec th{text-align:left;width:16rem;vertical-align:top;padding:.35rem .8rem .35rem 0;
   color:var(--mut);font-weight:normal;border-bottom:1px solid var(--line)}
table.spec td{padding:.35rem 0;border-bottom:1px solid var(--line);
   font-family:'Liberation Mono',monospace;font-size:.86rem}
pre{background:var(--code);padding:1rem;overflow-x:auto;border-radius:3px;
    font-size:.82rem;line-height:1.5}
code{background:var(--code);padding:.1rem .3rem;border-radius:2px;font-size:.86em}
.box{border-left:4px solid var(--ink);padding:.2rem 0 .2rem 1rem;margin:1.2rem 0}
.box.warn{border-color:var(--warn)}
.box.ok{border-color:var(--ok)}
.meta{color:var(--mut);font-size:.85rem}
.pill{display:inline-block;border:1px solid var(--line);border-radius:2rem;
      padding:.05rem .6rem;font-size:.75rem;color:var(--mut);margin-right:.3rem}
@media (prefers-color-scheme:dark){
 :root{--ink:#e9e5dc;--mut:#9d978a;--pap:#16150f;--line:#3a372f;--code:#211f18;
       --warn:#e08a72;--ok:#8fc8a6}
}
</style>
<div class=wrap>
<h1>Image Prompt Library</h1>
<p class=lede><em>The Great Book of World Games</em> — the canonical record of
every image prompt written for this book, including the ones that were
rejected.</p>
<div class="box">
<p><strong>How this file works.</strong> Each section is fenced by an HTML
comment marker and is regenerated by a single build script. Nothing outside a
section is ever touched, and no section is deleted. A prompt library is only
useful if it keeps its failures: the rejected prompt is what stops the same
mistake being made twice.</p>
</div>
__SECTIONS__
</div>
"""


def section_html(root, cfg, geo) -> str:
    from prompt_text import (NO_TEXT_BLOCK, AVOID_BLOCK, COVER_01, COVER_02,
                             APLUS_MODULES)
    pb = geo["editions"]["paperback"]
    hc = geo["editions"].get("hardcover")
    a = pb["artworkTarget"]
    z, sz = pb["zones"], pb["safeZones"]
    tw, th = pb["trimWidthIn"], pb["trimHeightIn"]
    bl = pb["bleedIn"]
    front_w_in = tw + bl
    ratio_wrap = pb["wrapWidthIn"] / pb["wrapHeightIn"]
    ratio_front = front_w_in / pb["wrapHeightIn"]
    min_gen_w = int(-(-a["widthPx"] // 4))
    min_gen_h = int(-(-a["heightPx"] // 4))
    fmin_w = int(-(-a["frontOnlyWidthPx"] // 4))
    fmin_h = int(-(-a["frontOnlyHeightPx"] // 4))

    def zone_row(label, key):
        b = sz[key]
        return (label, "x %.3f–%.3f in · y %.3f–%.3f in  (%d–%d px × %d–%d px "
                "@300 ppi)" % (b["x0"], b["x1"], b["y0"], b["y1"],
                               round(b["x0"] * 300), round(b["x1"] * 300),
                               round(b["y0"] * 300), round(b["y1"] * 300)))

    def cover_block(c):
        return "".join([
            "<h3>%s</h3>" % E(c["title"]),
            "<p>%s</p>" % E(c["concept"]),
            "<h4>Art direction</h4>", ul(c["direction"]),
            "<h4>Composition — this is the part that decides whether the cover "
            "works</h4>", ul(c["composition"]),
            "<h4>Absolute prohibitions</h4>", ul(NO_TEXT_BLOCK, "no"),
            "<h4>Avoid</h4>", ul(AVOID_BLOCK, "avoid"),
            "<h4>Output contract</h4>",
            kv([
                ("Asset ID", c["id"]),
                ("Raw filename (full wrap)", "%s-wrap.png" % c["slug"]),
                ("Raw filename (front only)", "%s-front.png" % c["slug"]),
                ("Raw location", "07_ASSETS/raw/cover/"),
                ("Format", "PNG, 8-bit RGB, sRGB, no alpha channel"),
                ("Wrap aspect ratio", "%.4f : 1 (%.4f × %.4f in)"
                 % (ratio_wrap, pb["wrapWidthIn"], pb["wrapHeightIn"])),
                ("Wrap target at 300 ppi", "%d × %d px"
                 % (a["widthPx"], a["heightPx"])),
                ("Wrap minimum before upscaling", "%d × %d px  (×4 → %d × %d)"
                 % (min_gen_w, min_gen_h, min_gen_w * 4, min_gen_h * 4)),
                ("Front-only aspect ratio", "%.4f : 1 (%.4f × %.4f in)"
                 % (ratio_front, front_w_in, pb["wrapHeightIn"])),
                ("Front-only target at 300 ppi", "%d × %d px"
                 % (a["frontOnlyWidthPx"], a["frontOnlyHeightPx"])),
                ("Front-only minimum before upscaling",
                 "%d × %d px  (×4 → %d × %d)"
                 % (fmin_w, fmin_h, fmin_w * 4, fmin_h * 4)),
                ("Bleed", "%.3f in on all four sides — artwork must run into "
                          "it and nothing may be composed there" % bl),
                ("Crop-safe area", "%.2f in inside the trim on all four sides"
                 % pb["safeIn"]),
                zone_row("Front title-safe zone", "frontTitle"),
                zone_row("Author-safe zone", "frontAuthor"),
                zone_row("Spine-safe zone", "spineText"),
                zone_row("Back-copy-safe zone", "backCopy"),
                zone_row("Barcode keep-clear", "barcode"),
                ("Panel boundaries on the wrap",
                 "back %.3f–%.3f in · spine %.3f–%.3f in · front %.3f–%.3f in"
                 % (z["backCover"]["x0"], z["backCover"]["x1"],
                    z["spine"]["x0"], z["spine"]["x1"],
                    z["frontCover"]["x0"], z["frontCover"]["x1"])),
            ]),
        ])

    def aplus_block(m):
        return "".join([
            "<h3>A+ MODULE %s — %s</h3>" % (E(m["n"]), E(m["name"])),
            '<p><span class=pill>%s</span><span class=pill>%d × %d px</span>'
            '<span class=pill>%.3f : 1</span></p>'
            % (E(m["module"]), m["w"], m["h"], m["w"] / m["h"]),
            "<h4>Purpose</h4><p>%s</p>" % E(m["purpose"]),
            "<h4>Prompt</h4>", ul(m["prompt"]),
            "<h4>Text-safe area</h4><p>%s</p>" % E(m["safe"]),
            "<h4>Output contract</h4>",
            kv([
                ("Module ID", m["id"]),
                ("Amazon module type", m["module"]),
                ("Filename", "%s.png" % m["slug"]),
                ("Raw location", "07_ASSETS/raw/aplus/"),
                ("Exact target dimensions", "%d × %d px" % (m["w"], m["h"])),
                ("Aspect ratio", "%.4f : 1" % (m["w"] / m["h"])),
                ("Generate at", "at least %d × %d px, then crop to ratio and "
                                "downscale — see the note on upscaling below"
                 % (m["w"] * 2, m["h"] * 2)),
                ("Format", "PNG or JPG, sRGB, under 2 MB"),
                ("Text in image", "NONE. All copy goes in Amazon's own title "
                                  "and body fields."),
                ("Answer content", "NONE. No rules, no solutions, no readable "
                                   "page content."),
            ]),
            "<h4>Absolute prohibitions</h4>", ul(NO_TEXT_BLOCK, "no"),
        ])

    parts = [
        '<!-- SECTION:%s -->' % SECTION_ID,
        '<h2>Final Phase 6 Cover + A+ Asset Prompts</h2>',
        '<p class=meta>Generated by <code>04_BUILD/build_prompt_library.py</code>'
        ' · geometry from <code>06_REPORTS/cover-geometry.json</code>'
        ' · measured page count <strong>%d</strong> · spine '
        '<strong>%.4f in</strong></p>' % (pb["pageCount"], pb["spineWidthIn"]),

        '<div class="box warn"><p><strong>Every number on this page is '
        'measured, not chosen.</strong> The spine width comes from the page '
        'count that <code>interior.py</code> actually counted, and the page '
        'count changes if the interior changes. If you rebuild the interior, '
        'rebuild this file before you generate art. Artwork produced against a '
        'stale spine is unusable — the fold lands in the wrong place and the '
        'front cover is cropped.</p></div>',

        '<div class="box"><p><strong>Why the artwork carries no lettering.</strong> '
        'All type on this cover is set afterwards as vector text by '
        '<code>04_BUILD/covers.py</code>, from the project metadata. That is '
        'not a stylistic preference. Type baked into a generated image cannot '
        'be corrected, cannot be kerned, prints soft at 300 dpi, and — with '
        'image models — is very often subtly misspelled in a way nobody '
        'notices until the proof copy arrives. The artwork is a surface. The '
        'words are set on it.</p></div>',

        '<h3>Founder workflow</h3>',
        '<ol>'
        '<li>Generate the artwork externally, using the prompts below.</li>'
        '<li>Save the raw files, unmodified, into <code>07_ASSETS/raw/cover/</code> '
        'and <code>07_ASSETS/raw/aplus/</code> using the exact filenames given '
        'in each output contract.</li>'
        '<li>Run <code>python3 04_BUILD/cover_artwork.py</code>. It checksums '
        'every raw file, measures its real effective DPI against the target '
        'trim, and tells you whether it needs upscaling.</li>'
        '<li>Nothing overwrites a raw file, ever. Processing writes new files '
        'into <code>07_ASSETS/processed/</code> and <code>print/</code>.</li>'
        '</ol>',

        '<h3>On resolution, and the difference that matters</h3>',
        '<div class="box"><p>There are two different things people call '
        '"300 DPI" and only one of them is real.</p>'
        '<p><strong>Writing a 300 DPI tag into the file changes nothing.</strong> '
        'The pixel count is what prints. A 1024-pixel-wide image labelled '
        '300 DPI is still a 1024-pixel-wide image, and at 8.5 inches wide it '
        'prints at 120 effective DPI and looks like it.</p>'
        '<p><strong>Effective DPI is arithmetic:</strong> '
        '<code>pixels ÷ physical inches</code>. For this cover the front panel '
        'is %.3f in wide including bleed, so a raw file needs at least '
        '<strong>%d px</strong> across it to reach 300 effective DPI. That is '
        'the number to check, and <code>cover_artwork.py</code> checks it.</p>'
        '<p>The project\'s approved route to more pixels is real AI upscaling, '
        'not resampling — see <code>ASSET_UPSCALING_REPORT.md</code>, which is '
        'authoritative. The installed engine is '
        '<code>~/Applications/upscayl-cli/upscayl-bin</code> and the model to '
        'prefer for illustrated cover art is <code>digital-art-4x</code>.</p></div>'
        % (front_w_in, a["frontOnlyWidthPx"]),

        '<pre># The approved pipeline (ASSET_UPSCALING_REPORT.md §4.1)\n'
        'UPSCAYL=~/Applications/upscayl-cli/upscayl-bin\n'
        '"$UPSCAYL" -i raw.png -o raw-4x-300dpi.png \\\n'
        '           -n digital-art-4x -s 4 -g 0 -f png\n'
        'python3 -c "from PIL import Image; im=Image.open(\'raw-4x-300dpi.png\');'
        ' im.save(\'raw-4x-300dpi.png\', dpi=(300,300))"</pre>',

        '<div class="box ok"><p><strong>A+ images do not need upscaling.</strong> '
        'The largest A+ image in this set is 970 px wide. Any current image '
        'model produces more pixels than that. A+ art should be generated '
        'large, cropped to the exact ratio, and <em>downscaled</em> with a '
        'good filter. Running a 4× upscaler on an image you are about to '
        'shrink adds artefacts and nothing else.</p></div>',

        '<h2 style="border-top-width:1px">Cover prompts</h2>',
        cover_block(COVER_01),
        cover_block(COVER_02),

        '<h3>Choosing between them</h3>',
        '<p>Both are generated; one is selected. <code>covers.py</code> '
        'composes whichever is promoted, and the selection is recorded rather '
        'than assumed. The criteria, in the order they are applied: thumbnail '
        'readability at 120 px; visual hierarchy on the front panel; '
        'continuity across the spine; a genuinely quiet title zone; a genuinely '
        'quiet author zone; a back panel that can carry body text without a '
        'box behind it; cultural integrity — nothing sacred, nothing fused, '
        'nothing invented; and commercial presence beside the other books on '
        'the shelf.</p>',

        '<h2 style="border-top-width:1px">A+ content prompts</h2>',
        '<div class="box"><p><strong>The A+ text policy is absolute.</strong> '
        'No generated image in this set contains a single character. Titles '
        'and body copy are entered into Amazon\'s own module fields, where '
        'they are searchable, correctable and translatable. The mapping is '
        '<em>module → image → title → body</em>, and the text half lives in '
        '<code>03_APLUS/aplus_content.json</code>, not in a picture.</p></div>',
        "".join(aplus_block(m) for m in APLUS_MODULES),

        '<h3>A+ module dimensions — verify before upload</h3>',
        '<p class=meta>The pixel sizes above are Amazon\'s published module '
        'dimensions as recorded for this build. Amazon revises the A+ module '
        'set from time to time. <strong>Founder action:</strong> open the A+ '
        'module picker in the KDP Marketing tab and confirm each module\'s '
        'stated image size before generating final art. If a size has changed, '
        'update <code>04_BUILD/prompt_text.py</code> and rebuild this page.</p>',
    ]
    if hc:
        parts.append(
            '<h3>Hardcover</h3><p class=meta>The hardcover wrap is a different '
            'shape: trim %.2f × %.2f in, spine %.4f in, wrap %.4f × %.4f in '
            '(%d × %d px at 300 ppi). Its geometry is a <strong>hypothesis '
            'pending the KDP hardcover template</strong>, which includes board '
            'thickness, hinge and wrap allowances that cannot be derived from '
            'the page count alone. <strong>Founder action:</strong> download '
            'the hardcover template from KDP and confirm before generating a '
            'hardcover-specific wrap. The paperback artwork can be re-cropped '
            'for hardcover once the template is confirmed.</p>'
            % (hc["trimWidthIn"], hc["trimHeightIn"], hc["spineWidthIn"],
               hc["wrapWidthIn"], hc["wrapHeightIn"],
               hc["artworkTarget"]["widthPx"], hc["artworkTarget"]["heightPx"]))
    parts.append('<!-- /SECTION:%s -->' % SECTION_ID)
    return "\n".join(parts)


def build(root: str) -> int:
    cfg = load(os.path.join(root, "project_config.json"))
    gp = os.path.join(root, "06_REPORTS", "cover-geometry.json")
    if not os.path.exists(gp):
        print("  ⛔ kapak geometrisi yok — önce 04_BUILD/covers.py koşun")
        return 1
    geo = load(gp)
    if "paperback" not in geo.get("editions", {}):
        print("  ⛔ ciltsiz geometrisi yok")
        return 1

    new = section_html(root, cfg, geo)
    path = os.path.join(root, OUT_REL)
    open_tag = "<!-- SECTION:%s -->" % SECTION_ID
    close_tag = "<!-- /SECTION:%s -->" % SECTION_ID

    if os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            cur = fh.read()
        if open_tag in cur and close_tag in cur:
            a = cur.index(open_tag)
            b = cur.index(close_tag) + len(close_tag)
            out = cur[:a] + new + cur[b:]
            action = "bölüm yenilendi (geçmiş korundu)"
        else:
            out = cur.replace("__SECTIONS__", "__SECTIONS__\n" + new, 1) \
                if "__SECTIONS__" in cur else cur + "\n" + new
            action = "bölüm EKLENDİ (geçmiş korundu)"
    else:
        out = SHELL.replace("__SECTIONS__", new)
        action = ("dosya OLUŞTURULDU — Faz 5 bu teslimatı üretmemişti "
                  "(EDITORIAL_ARCHITECTURE § 4)")

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("  ✓ %s" % OUT_REL)
    print("    %s" % action)
    print("    %d bayt · sırt %.4f in · %d sayfa"
          % (len(out.encode()), geo["editions"]["paperback"]["spineWidthIn"],
             geo["editions"]["paperback"]["pageCount"]))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=DEFAULT_ROOT)
    args = ap.parse_args()
    print("=" * 74)
    print("  GÖRSEL İSTEM KÜTÜPHANESİ")
    print("=" * 74)
    rc = build(os.path.abspath(args.root))
    print("=" * 74)
    return rc


if __name__ == "__main__":
    sys.exit(main())
